In [11]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

# Imports
import numpy as np
import tensorflow as tf

a = tf.placeholder(tf.float32,shape = [3,])
b = tf.placeholder(tf.float32,shape = [3,])

c = tf.confusion_matrix(labels = a, predictions = b)

with tf.Session() as sess:
    print(c.eval(feed_dict={a:[1, 2, 4],b:[2, 2, 4]}))


[[0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 1]]
